-- Shipped key policy. Compiled at build time into the native input map.
-- User init.lua can replace any binding with lemma.keymap.set/del or preset="none".

context("normal", "", "persistent", "forward", false)
context("prefix", "", "one_shot", "replay_deferred", false)
context("resize", "RESIZE", "persistent", "consume", true)
context("copy", "COPY", "persistent", "consume", false)
context("copy_go", "", "one_shot", "retry_base", false)
context("copy_search", "SEARCH", "persistent", "forward", false)
context("copy_searching", "SEARCH", "persistent", "consume", false)
context("rename", "RENAME", "persistent", "forward", false)
context("command_line", "COMMAND", "persistent", "forward", false)
context("messages", "LOG", "persistent", "consume", false)

prefix("C-b")

bind("prefix", "d", "detach", "retain")
bind("prefix", "m", "push", "resize")
bind("prefix", "%", "split_left_right", "retain")
bind("prefix", "\"", "split_top_bottom", "retain")
bind("prefix", "h", "focus_left", "retain")
bind("prefix", "j", "focus_down", "retain")
bind("prefix", "k", "focus_up", "retain")
bind("prefix", "l", "focus_right", "retain")
bind("prefix", "H", "swap_pane_left", "retain")
bind("prefix", "J", "swap_pane_down", "retain")
bind("prefix", "K", "swap_pane_up", "retain")
bind("prefix", "L", "swap_pane_right", "retain")
bind("prefix", "o", "focus_next", "retain")
bind("prefix", ";", "focus_previous", "retain")
bind("prefix", "x", "close_pane", "retain")
bind("prefix", "z", "toggle_zoom", "retain")
bind("prefix", "c", "create_tab", "retain")
bind("prefix", "n", "next_tab", "retain")
bind("prefix", "p", "previous_tab", "retain")
bind("prefix", "P", "move_tab_left", "retain")
bind("prefix", "N", "move_tab_right", "retain")
bind("prefix", "&", "close_tab", "retain")
bind("prefix", "[", "enter_copy_mode", "base")
bind("prefix", "/", "enter_copy_search_forward", "base")
bind("prefix", "?", "enter_copy_search_backward", "base")
bind("prefix", "R", "begin_rename_session", "base")
bind("prefix", "r", "begin_rename_tab", "base")
bind("prefix", ":", "begin_command_line", "base")
bind("prefix", "~", "show_messages", "base")
bind("prefix", "0", "select_tab_0", "retain")
bind("prefix", "1", "select_tab_1", "retain")
bind("prefix", "2", "select_tab_2", "retain")
bind("prefix", "3", "select_tab_3", "retain")
bind("prefix", "4", "select_tab_4", "retain")
bind("prefix", "5", "select_tab_5", "retain")
bind("prefix", "6", "select_tab_6", "retain")
bind("prefix", "7", "select_tab_7", "retain")
bind("prefix", "8", "select_tab_8", "retain")
bind("prefix", "9", "select_tab_9", "retain")
bind("normal", "Super-c", "copy_selection", "retain")
bind("prefix", "Super-c", "copy_selection", "retain")
bind("resize", "Super-c", "copy_selection", "retain")
bind("normal", "C-S-c", "copy_selection", "retain")
bind("prefix", "C-S-c", "copy_selection", "retain")
bind("resize", "C-S-c", "copy_selection", "retain")
bind("normal", "Super-Left", "send", "Home")
bind("prefix", "Super-Left", "send", "Home")
bind("normal", "Super-Right", "send", "End")
bind("prefix", "Super-Right", "send", "End")
bind("normal", "S-Super-Left", "send", "S-Home")
bind("prefix", "S-Super-Left", "send", "S-Home")
bind("normal", "S-Super-Right", "send", "S-End")
bind("prefix", "S-Super-Right", "send", "S-End")
bind("prefix", "C-h", "resize_left", "retain")
bind("prefix", "C-S-h", "resize_left", "retain")
bind("prefix", "M-h", "resize_left", "retain")
bind("prefix", "S-M-h", "resize_left", "retain")
bind("resize", "h", "resize_left", "retain")
bind("prefix", "C-j", "resize_down", "retain")
bind("prefix", "C-S-j", "resize_down", "retain")
bind("prefix", "M-j", "resize_down", "retain")
bind("prefix", "S-M-j", "resize_down", "retain")
bind("resize", "j", "resize_down", "retain")
bind("prefix", "C-k", "resize_up", "retain")
bind("prefix", "C-S-k", "resize_up", "retain")
bind("prefix", "M-k", "resize_up", "retain")
bind("prefix", "S-M-k", "resize_up", "retain")
bind("resize", "k", "resize_up", "retain")
bind("prefix", "C-l", "resize_right", "retain")
bind("prefix", "C-S-l", "resize_right", "retain")
bind("prefix", "M-l", "resize_right", "retain")
bind("prefix", "S-M-l", "resize_right", "retain")
bind("resize", "l", "resize_right", "retain")
bind("resize", "Left", "resize_left", "retain")
bind("resize", "Down", "resize_down", "retain")
bind("resize", "Up", "resize_up", "retain")
bind("resize", "Right", "resize_right", "retain")
bind("resize", "q", "pop")
bind("resize", "Enter", "pop")
bind("resize", "Escape", "pop")
bind("resize", "C-c", "pop")
bind("resize", "C-g", "pop")
bind("copy", "Escape", "copy_cancel_or_leave", "retain")
bind("copy", "C-c", "copy_leave", "retain")
bind("copy", "C-g", "copy_leave", "retain")
bind("copy", "q", "copy_leave", "retain")
bind("copy", "h", "copy_move_left", "retain")
bind("copy", "j", "copy_move_down", "retain")
bind("copy", "k", "copy_move_up", "retain")
bind("copy", "l", "copy_move_right", "retain")
bind("copy", "b", "copy_word_left", "retain")
bind("copy", "w", "copy_word_right", "retain")
bind("copy", "e", "copy_word_end", "retain")
bind("copy", "0", "copy_line_start", "retain")
bind("copy", "^", "copy_line_first_nonblank", "retain")
bind("copy", "$", "copy_line_end", "retain")
bind("copy", "G", "copy_history_bottom", "retain")
bind("copy", "H", "copy_viewport_top", "retain")
bind("copy", "M", "copy_viewport_middle", "retain")
bind("copy", "L", "copy_viewport_bottom", "retain")
bind("copy", "Space", "copy_visual_character", "retain")
bind("copy", "v", "copy_visual_character", "retain")
bind("copy", "V", "copy_visual_line", "retain")
bind("copy", "o", "copy_swap_endpoint", "retain")
bind("copy", "y", "copy_selection", "retain")
bind("copy", "/", "enter_copy_search_forward", "retain")
bind("copy", "?", "enter_copy_search_backward", "retain")
bind("copy", "n", "copy_repeat_search", "retain")
bind("copy", "N", "copy_reverse_search", "retain")
bind("copy", "g", "push", "copy_go")
bind("copy_go", "g", "copy_history_top", "base")
bind("copy", "C-u", "copy_half_page_up", "retain")
bind("copy", "C-d", "copy_half_page_down", "retain")
bind("copy", "C-f", "copy_page_down", "retain")
bind("copy", "C-v", "copy_visual_block", "retain")
bind("copy", "Enter", "copy_selection", "retain")
bind("copy", "C-j", "copy_selection", "retain")
bind("copy", "Left", "copy_move_left", "retain")
bind("copy", "Down", "copy_move_down", "retain")
bind("copy", "Up", "copy_move_up", "retain")
bind("copy", "Right", "copy_move_right", "retain")
bind("copy", "Home", "copy_line_start", "retain")
bind("copy", "End", "copy_line_end", "retain")
bind("copy", "PageUp", "copy_page_up", "retain")
bind("copy", "PageDown", "copy_page_down", "retain")
bind("copy_search", "Escape", "copy_cancel_search", "retain")
bind("copy_searching", "Escape", "copy_cancel_search", "retain")
bind("copy_search", "Backspace", "copy_query_backspace", "retain")
bind("copy_search", "C-h", "copy_query_backspace", "retain")
bind("copy_search", "Enter", "copy_commit_search", "retain")
bind("copy_search", "C-j", "copy_commit_search", "retain")
bind("copy_searching", "C-c", "copy_leave", "retain")
bind("copy_searching", "C-g", "copy_leave", "retain")
bind("copy_searching", "q", "copy_leave", "retain")
bind("rename", "Escape", "rename_cancel", "retain")
bind("rename", "C-c", "rename_cancel", "retain")
bind("rename", "C-g", "rename_cancel", "retain")
bind("rename", "Enter", "rename_commit", "retain")
bind("rename", "C-j", "rename_commit", "retain")
bind("rename", "Backspace", "rename_backspace", "retain")
bind("rename", "C-h", "rename_backspace", "retain")
bind("rename", "Delete", "rename_delete", "retain")
bind("rename", "Left", "rename_cursor_left", "retain")
bind("rename", "Right", "rename_cursor_right", "retain")
bind("rename", "C-a", "rename_cursor_home", "retain")
bind("rename", "Home", "rename_cursor_home", "retain")
bind("rename", "C-e", "rename_cursor_end", "retain")
bind("rename", "End", "rename_cursor_end", "retain")
bind("rename", "C-u", "rename_clear", "retain")
bind("rename", "C-w", "rename_delete_word", "retain")
bind("command_line", "Escape", "command_line_cancel", "retain")
bind("command_line", "C-c", "command_line_cancel", "retain")
bind("command_line", "C-g", "command_line_cancel", "retain")
bind("command_line", "Enter", "command_line_commit", "retain")
bind("command_line", "C-j", "command_line_commit", "retain")
bind("command_line", "Tab", "command_line_complete", "retain")
bind("command_line", "Backspace", "command_line_backspace", "retain")
bind("command_line", "C-h", "command_line_backspace", "retain")
bind("command_line", "Delete", "command_line_delete", "retain")
bind("command_line", "Left", "command_line_cursor_left", "retain")
bind("command_line", "Right", "command_line_cursor_right", "retain")
bind("command_line", "Up", "command_line_history_previous", "retain")
bind("command_line", "Down", "command_line_history_next", "retain")
bind("command_line", "C-a", "command_line_cursor_home", "retain")
bind("command_line", "Home", "command_line_cursor_home", "retain")
bind("command_line", "C-e", "command_line_cursor_end", "retain")
bind("command_line", "End", "command_line_cursor_end", "retain")
bind("command_line", "C-u", "command_line_clear", "retain")
bind("command_line", "C-w", "command_line_delete_word", "retain")
bind("messages", "Escape", "message_view_leave", "retain")
bind("messages", "C-c", "message_view_leave", "retain")
bind("messages", "C-g", "message_view_leave", "retain")
bind("messages", "q", "message_view_leave", "retain")
bind("messages", "Enter", "message_view_leave", "retain")
bind("messages", "k", "message_view_previous", "retain")
bind("messages", "Up", "message_view_previous", "retain")
bind("messages", "j", "message_view_next", "retain")
bind("messages", "Down", "message_view_next", "retain")
bind("messages", "PageUp", "message_view_page_previous", "retain")
bind("messages", "C-f", "message_view_page_next", "retain")
bind("messages", "PageDown", "message_view_page_next", "retain")
bind("messages", "g", "message_view_history_start", "retain")
bind("messages", "Home", "message_view_history_start", "retain")
bind("messages", "G", "message_view_history_end", "retain")
bind("messages", "End", "message_view_history_end", "retain")
